### PR TITLE
Add color support to UIUtils.applyMarkup

### PR DESCRIPTION
**Pull request by jordane-quincy**
Add BBCode support for color tag in FavouritesListFragment, NowPlayingFragment, PlaylistFragment, RemoteFragment and NowPlayingPanel
Linked to #629

### CODE REVIEW

**Comment by jordane-quincy** [comment]
I don't have IPTV so it's harder for me to test/debug it but add support to fill #191 should be trivial.
I can add it to this PR if someone tell me where to put the code (PVRChannelsListFragment ?).

**Comment by SyncedSynapse** [comment]
This looks good. Unfortunately i haven't found an example of titles using color, so i haven't really tested it... Can you point me to an example.

Regarding implementing this on the PVR side, it should be straightforward. As you say, just put it on `PVRChannelsListFragment`, on the `GetView` of both `ChannelGroupAdapter` and `ChannelAdapter`.

Sorry for the delay.

**Comment by dagwieers** [comment]
If you install **plugin.video.vrt.nu** you can browse menus that have bold and colors used in titles (in the TV guide). The add-on should work fine for all menus, playback may not work though.

**Comment by jordane-quincy** [comment]
@dagwieers : I've installed it but I got an error, preventing me to open the TV guide.

@SyncedSynapse : Sorry for the delay, I wasn't at home for a while.
I've applied the markup to `GetView` of `ChannelGroupAdapter` but it seems to be already there for `ChannelAdapter` [commit 206b5c9](https://github.com/xbmc/Kore/commit/206b5c9).
Did I miss something ?

**Comment by dagwieers** [comment]
@jordane-quincy That may be geo-blocked then. Can you try to open the **Recent items** or **Soon offline** menus?

**Comment by SyncedSynapse** [comment]
@jordane-quincy Sorry you didn't miss anything, it was already there.

I'm good with this, but you've included 2 PRs that were already in master (soundcloud support and sk language), which causes this to not apply cleanly. Can you please rebase your changes on the current master and submit just the changes you've made.

If you're not familiar with git, maybe @poisdeux  can help.

**Comment by jordane-quincy** [comment]
@SyncedSynapse It should be good now

**Comment by dagwieers** [comment]
When can we expect a new beta version on Google Play Store?
I would like to test the latest changes and bugfixes.

**Comment by SyncedSynapse** [comment]
I plan to make a new release soon, i just want to include the PRs that are currently open. 
In the meantime, if you are able to side load android apps, you can get an updated version at:
http://mirrors.kodi.tv/tools/kore/nightlies/

**Comment by dagwieers** [comment]
Unfortunately this doesn't fix the BBCode tags from titles in listings.
Which is most inconvenient.

**Pull request merged**
