### PR TITLE
unit test IDE execution improvements

### PR DESCRIPTION
**Pull request by Calebzor**
I was having trouble with running the unit tests locally. With this solution the unit tests can be run one by one from the IDE on the already checked in test json files.

What I did is: load the test data json files from the file system with standard java instead of through android context in order to allow more convenient execution of unit tests.

I've only tested this on Windows.

### CODE REVIEW

**Comment by Calebzor** [comment]
Ohh well, looks like the CI does not like it yet. I'll check out what's going wrong on Linux.

**Comment by poisdeux** [comment]
I don't understand what the problem is you are trying to solve. I admit the current setup has only been tested on Linux and MacOS. But I believe that even on Windows the android gradle plugin should handle the assets inclusion.
https://github.com/xbmc/Kore/blob/master/app/build.gradle#L42

Did you run the `testFullDebugUnitTest` or `testInstrumentationTestDebugUnitTest`? As described in https://github.com/xbmc/Kore/blob/master/app/src/test/README.md

**Comment by Calebzor** [comment]
Hi @poisdeux 

Yes while `gradlew.bat testFullDebugUnitTest` works.

> Select build variant "instrumentationTestDebug"
Set the (Project view)[https://developer.android.com/studio/projects/index.html] to Android
Right-click on the directory "test" and select "Run tests"

This does not work for me. What I get is:

```
java.io.FileNotFoundException: build\intermediates\bundles\instrumentationTest\debug\assets\Video.Details.Movie.json (The system cannot find the path specified)

	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.robolectric.res.FileFsFile.getInputStream(FileFsFile.java:78)
	at org.robolectric.shadows.ShadowAssetManager.open(ShadowAssetManager.java:179)
	at android.content.res.AssetManager.open(AssetManager.java)
	at org.xbmc.kore.testutils.FileUtils.readFile(FileUtils.java:26)
	at org.xbmc.kore.testutils.Database.insertMovies(Database.java:87)
	at org.xbmc.kore.testutils.Database.fill(Database.java:48)
	at org.xbmc.kore.provider.mediaprovider.AbstractTestClass.setUp(AbstractTestClass.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:248)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:174)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:63)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:140)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Which is not that surprising considering in the IDE's gradle console this is what I see:
```
Executing tasks: [:app:generateInstrumentationTestDebugSources, :app:prepareInstrumentationTestDebugUnitTestDependencies, :app:mockableAndroidJar, :app:compileInstrumentationTestDebugUnitTestSources]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\android-sdks\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preInstrumentationTestDebugBuild UP-TO-DATE
:app:checkInstrumentationTestDebugManifest
:app:preFullDebugBuild UP-TO-DATE
:app:extractProguardFiles
:app:preFullReleaseBuild
:app:preInstrumentationTestReleaseBuild
:app:prepareAtBlogcExpandabletextview103Library
:app:prepareComAndroidSupportAnimatedVectorDrawable2501Library
:app:prepareComAndroidSupportAppcompatV72501Library
:app:prepareComAndroidSupportCardviewV72501Library
:app:prepareComAndroidSupportPreferenceV142501Library
:app:prepareComAndroidSupportPreferenceV72501Library
:app:prepareComAndroidSupportRecyclerviewV72501Library
:app:preFullDebugAndroidTestBuild UP-TO-DATE
:app:preInstrumentationTestDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportSupportCompat2501Library
:app:prepareComAndroidSupportSupportCoreUi2501Library
:app:prepareComAndroidSupportSupportCoreUtils2501Library
:app:prepareComAndroidSupportSupportFragment2501Library
:app:prepareComAndroidSupportSupportMediaCompat2501Library
:app:prepareComAndroidSupportSupportV132501Library
:app:prepareComAndroidSupportSupportV42501Library
:app:prepareComAndroidSupportSupportVectorDrawable2501Library
:app:prepareComAstuetzPagerslidingtabstrip101Library
:app:prepareComMelnykovFloatingactionbutton130Library
:app:prepareComSothreeSlidinguppanelLibrary331Library
:app:prepareInstrumentationTestDebugDependencies
:app:compileInstrumentationTestDebugAidl UP-TO-DATE
:app:compileInstrumentationTestDebugRenderscript UP-TO-DATE
:app:generateInstrumentationTestDebugBuildConfig UP-TO-DATE
:app:generateInstrumentationTestDebugResValues UP-TO-DATE
:app:generateInstrumentationTestDebugResources UP-TO-DATE
:app:mergeInstrumentationTestDebugResources UP-TO-DATE
:app:processInstrumentationTestDebugManifest UP-TO-DATE
:app:processInstrumentationTestDebugResources UP-TO-DATE
:app:generateInstrumentationTestDebugSources UP-TO-DATE
:app:preInstrumentationTestDebugUnitTestBuild UP-TO-DATE
:app:prepareInstrumentationTestDebugUnitTestDependencies
:app:mockableAndroidJar UP-TO-DATE
:app:incrementalInstrumentationTestDebugJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileInstrumentationTestDebug
:app:compileInstrumentationTestDebugJavaWithJavac UP-TO-DATE
:app:incrementalInstrumentationTestDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileInstrumentationTestDebugUnitTest
:app:compileInstrumentationTestDebugUnitTestJavaWithJavac UP-TO-DATE
:app:processInstrumentationTestDebugJavaRes UP-TO-DATE
:app:processInstrumentationTestDebugUnitTestJavaRes UP-TO-DATE
:app:compileInstrumentationTestDebugUnitTestSources UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.099 secs

```

No mention of `testFullDebugUnitTest`.

This is also the type of exception I get when I try to run a single test class from the IDE say `GenresTest`.

My goal here in this PR is to allow running any unit tests on it's own from within the IDE.

My concern is that the whole test suit only consists of 33 test (1 ignored) yet it takes about `54.528 secs` to run `testFullDebugUnitTest`. In my opinion this is too long for so few tests. So to help with running new (hopefully faster) unit tests, developers should be able to run their own tests (or a subset of tests) from the IDE without them failing because of asset setup is not working for such a scenario.

**Comment by poisdeux** [comment]
Oops, sorry about that. I've updated the docs in PR #460.

Actually the `testInstrumentationTestDebugUnitTest` should still work AFAICT from the gradle file. However, we use `fullDebugUnitTest` on travis-ci, so it never occurred to me that the `instrumentationTest` flavour is broken for local tests.

But your solution is not the right way to fix this. It should be handled by the android gradle plugin.
However, I wouldn't bother fixing this for `instrumentationTest`. It is included only to be able to disable animations. But that can now be disabled using the android gradle plugin ( \o/ ) 

```
testOptions {
        animationsDisabled true
    }
``` 

So the `instrumentationTest` flavour will probably be removed and you should use the `fullDebug` flavour for local tests. This should also allow you to select individual tests.

Regarding your remark about performance, I wouldn't bother optimising just yet. 58 secs is fine and I wouldn't expect anyone to run these tests on each build. If you do want to do this, I suggest you implement running the local tests in the background so the build finishes quickly while the tests continue to run in the background and provide feedback a few seconds later...
Final remark, if you do want to optimise, have a look at the setUp method. I believe none of the tests actually changes the database so we only have to set it up once. But, well, you know what they say about premature optimisation...

**Comment by Calebzor** [comment]
Hi @poisdeux 

Just to try and make my point a bit more clear: I'm not having issues with running tests from command line.

Without these changes I can not run some tests individually (the ones that rely on DB setup from the .json asset files), because to me it looks like nothing makes them available where they are expected to be:
`java.io.FileNotFoundException: build\intermediates\bundles\full\debug\assets\Video.Details.Movie.json (The system cannot find the path specified)`
This is the main issue I was trying to address with this PR.

Having a global setup for **UNIT** tests is a big no-no for me. In my opinion **UNIT** tests need to set up and tear down everything for every test run. 

To be fair tests touching DB are not really unit tests in my opinion to begin with, so in that regard I see your point, but then for me the solution would be is to move tests that interact with a DB out (so they are not run along with "real" unit tests). Would you consider such an approach acceptable?

**Comment by poisdeux** [comment]
Could you test if the `fullDebug` flavour allows you to run individual tests? If so, this PR can be closed.

I agree that tests using a database aren't generally considered unit tests. That's why the tests under `test` are usually referred to as local tests. Meaning they do not require an Android device. We could add an extra layer below `test` to separate the fast from the slow tests or better yet use annotations. But what should be the criteria? 1 second, 2 seconds, 10 seconds, 1 minute? And what do we use as a reference build machine? An octacore with 128 GB RAM?

**Comment by Calebzor** [comment]
Without the code from the PR: From within the IDE I can **NOT** run individual tests with **ANY** flavor, including `fullDebug`. 

With the code from the PR:  I **CAN** run individual tests with **ANY** flavor, including `fullDebug`

I feel you are being a bit sarcastic there. :D

You'd generally use the most common developer machine for unit test speed measurement.  I'd say maximum 2 mins for 1000 unit tests, that's <=0.12s per test in average.

**Comment by poisdeux** [comment]
I am only able to reproduce your issue when using the `instrumentationTest` flavour.
I think this is more an issue with your Android Studio setup. However, I don't own a windows machine on which I can try to reproduce this. So, I think we should go with your fix. 
@SyncedSynapse do you by any chance have a Windows machine at your disposal and able to reproduce this issue?

Can you please refactor this PR to only include only the asset fix and create a separate PR for the performance issue? Than we can merge this and discuss the performance improvements further using the other PR.

**Comment by Calebzor** [comment]
The PR is only about asset inclusion already.

The kind of performance improvement I was talking about is perhaps just a perceived one. With this I can run just a single or a selected few tests, which is inherently faster than running all the unit tests.

**Comment by poisdeux** [comment]
I thought you added [readFile](https://github.com/xbmc/Kore/pull/459/files#diff-55c468d9fe7c208566afe48cde21a4b5R44) for performance reasons and the actual fix for the assets is in the gradle.build file. https://github.com/xbmc/Kore/pull/459/files#diff-39e7d8c00954e920b98e7636f0ac30b2R176

**Comment by Calebzor** [comment]
`copyUnitTestResources` is a new task that copies the json assets to a build flavor independent location. The other changes are there to load them from this location, instead of using the android context which then would use build flavor dependent path because of `context.getAssets()`.

**Comment by poisdeux** [comment]
Ah I see, thx for explaining. Good news, I was able to reproduce the issue on my build environment as well. (`./gradlew clean` did the trick...)

This problem seems similar to something I encountered when upgrading to android gradle plugin 2.3.3 in PR #431. To fix that, I made sure the `assembleFullDebug` was called to copy the assets. 

If we change `testFullDebugUnitTest` to `compileFullDebugUnitTestSources` in app/build.gradle on line [172](https://github.com/xbmc/Kore/blob/master/app/build.gradle#L172), it should work for running individual local tests as well. 
Can you confirm?

**Comment by Calebzor** [comment]
Nope, sorry. Still getting the same error even if I make the change you are proposing.

**Comment by poisdeux** [comment]
Can you post the Gradle Console output from Android Studio while running an individual test using the _fullDebug_ flavour?

**Comment by Calebzor** [comment]
```
Executing tasks: [:app:generateFullDebugSources, :app:prepareFullDebugUnitTestDependencies, :app:mockableAndroidJar, :app:compileFullDebugUnitTestSources]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\vatam\AppData\Local\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preFullDebugBuild UP-TO-DATE
:app:checkFullDebugManifest
:app:extractProguardFiles
:app:preFullReleaseBuild
:app:preInstrumentationTestDebugBuild UP-TO-DATE
:app:preInstrumentationTestReleaseBuild
:app:prepareAtBlogcExpandabletextview103Library
:app:prepareComAndroidSupportAnimatedVectorDrawable2501Library
:app:prepareComAndroidSupportAppcompatV72501Library
:app:prepareComAndroidSupportCardviewV72501Library
:app:prepareComAndroidSupportPreferenceV142501Library
:app:prepareComAndroidSupportPreferenceV72501Library
:app:prepareComAndroidSupportRecyclerviewV72501Library
:app:preFullDebugAndroidTestBuild UP-TO-DATE
:app:preInstrumentationTestDebugAndroidTestBuild UP-TO-DATE
:app:prepareComAndroidSupportSupportCompat2501Library
:app:prepareComAndroidSupportSupportCoreUi2501Library
:app:prepareComAndroidSupportSupportCoreUtils2501Library
:app:prepareComAndroidSupportSupportFragment2501Library
:app:prepareComAndroidSupportSupportMediaCompat2501Library
:app:prepareComAndroidSupportSupportV132501Library
:app:prepareComAndroidSupportSupportV42501Library
:app:prepareComAndroidSupportSupportVectorDrawable2501Library
:app:prepareComAstuetzPagerslidingtabstrip101Library
:app:prepareComMelnykovFloatingactionbutton130Library
:app:prepareComSothreeSlidinguppanelLibrary331Library
:app:prepareFullDebugDependencies
:app:compileFullDebugAidl UP-TO-DATE
:app:compileFullDebugRenderscript UP-TO-DATE
:app:generateFullDebugBuildConfig UP-TO-DATE
:app:generateFullDebugResValues UP-TO-DATE
:app:generateFullDebugResources UP-TO-DATE
:app:mergeFullDebugResources UP-TO-DATE
:app:processFullDebugManifest UP-TO-DATE
:app:processFullDebugResources UP-TO-DATE
:app:generateFullDebugSources UP-TO-DATE
:app:preFullDebugUnitTestBuild UP-TO-DATE
:app:prepareFullDebugUnitTestDependencies
:app:mockableAndroidJar UP-TO-DATE
:app:incrementalFullDebugJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileFullDebug
:app:compileFullDebugJavaWithJavac UP-TO-DATE
:app:compileFullDebugNdk UP-TO-DATE
:app:compileFullDebugSources UP-TO-DATE
:app:mergeFullDebugShaders UP-TO-DATE
:app:compileFullDebugShaders UP-TO-DATE
:app:generateFullDebugAssets UP-TO-DATE
:app:mergeFullDebugAssets UP-TO-DATE
:app:transformClassesWithDexForFullDebug UP-TO-DATE
:app:mergeFullDebugJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForFullDebug UP-TO-DATE
:app:processFullDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForFullDebug UP-TO-DATE
:app:validateSigningFullDebug
:app:packageFullDebug UP-TO-DATE
:app:assembleFullDebug UP-TO-DATE
:app:incrementalFullDebugUnitTestJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileFullDebugUnitTest
:app:compileFullDebugUnitTestJavaWithJavac UP-TO-DATE
:app:processFullDebugUnitTestJavaRes UP-TO-DATE
:app:compileFullDebugUnitTestSources UP-TO-DATE

BUILD SUCCESSFUL

Total time: 1.158 secs

```

**Comment by Calebzor** [comment]
OK, I've found what was the problem. For the run configuration in the IDE the `Working Directory` was not set, once I've set it to `MODULE_DIR` I could run single tests with only the `compileFullDebugUnitTestSources` change.

Maybe could add this tid-bit to the README.md

**Comment by Calebzor** [comment]
I'll close this and opened #463 instead.

**Pull request closed without merging**
