### PR TITLE
[jenkins] - fix sigining of apk

### PR DESCRIPTION
**Pull request by Memphiz**
what the title says ...

app-release-unsigned.apk vs. app-full-release-unsigned.apk

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build kore please

**Comment by Memphiz** [comment]
come on babe - jenkins build kore please

**Comment by MartijnKaijser** [comment]
i grabbed the APK from workspace and it installs fine

**Comment by SyncedSynapse** [comment]
Thanks all.

**Pull request merged**
