### PR TITLE
Create strings-zh-rTW

### PR DESCRIPTION
**Pull request by wstephen**
Wonderful APK!  Can't afford  the UI without not in my language for people living in the world of Traditional Chinese.

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
Can this be merged as is or are you still working on it?

**Comment by SyncedSynapse** [comment]
I would also appreciate if you could squash these commits into one.

**Comment by wstephen** [comment]
This can be merged now.  I am too picky.  Anyway, sure it is finalized for merging. I am sorry.  Let me find out how to delete those previous comments.  Please bear with me.

**Comment by SyncedSynapse** [comment]
Just noticed this, the directory should be values-zh-rTW...

**Comment by SyncedSynapse** [comment]
It will be easier if you close this PR and open a new one with the final strings.xml on the right place.

**Comment by wstephen** [comment]
How do I close this  PR please.

**Comment by SyncedSynapse** [comment]
It's closed. Now just submit a new one with the final file.

**Pull request closed without merging**
