### PR TITLE
Added playing or queueing artist/album/genre from music screen

### PR DESCRIPTION
**Pull request by poisdeux**
Implemented context menus in music items shown on the music screen. 
This allows the user to add everything from an artist, album, or genre by popping up the context menu and selecting either play or Add to playlist.

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
I will only be able to look and test this in a few weeks, but from a quick glance it looks good. Not sure about the name "MediaManager" for a class that just keeps utilities methods - MediaManager makes you think it does something "important", which it doesn't in this case, but i'll look into it in more detail later.

**Comment by SyncedSynapse** [comment]
Looks good. Like i said, i'm not a fan of the name "MediaManager" and i will probably change it to reflect its Utils nature.
Thanks.

**Comment by poisdeux** [comment]
How about MediaPlayerUtils?

**Comment by SyncedSynapse** [comment]
I've already changed it to MediaUtils, but that makes more sense, so i will change it again to that.

**Pull request merged**
