### PR TITLE
This implements feature request #103

### PR DESCRIPTION
**Pull request by poisdeux**
Added refresh menu item in overflow menu to allow user to refresh the content in *ListFragments and *DetailsFragments.

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
This conflicts with #135 . Can you check it please.

I also tried applying them in reverse order, but the conflict is also there.

**Comment by poisdeux** [comment]
Oops, sorry, I only checked it against master. I should have checked it against #135 as well. Should merge cleanly now.

**Comment by SyncedSynapse** [comment]
Ok. Any reason for removing the `@Override` from the `onStop` method on `AbstractDetailsFragment`?

**Comment by poisdeux** [comment]
Nope, *sigh* that's what I get when I do things inbetween...

**Comment by poisdeux** [comment]
fixed it.

**Pull request merged**
