### PR TITLE
Implemented unittests to test restoring search query

### PR DESCRIPTION
**Pull request by poisdeux**
* Added perl tools to generate json files for music and movie data
* Upgraded build tools version, sdk compile version, and support libraries
  as this is required by the test packages.
* Added new product flavor unittest to make sure assets and settings required
  for testing do not also ship with a release version of Kore

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
This needs to be put on hold, as upgrading the target-sdk to version 23 automatically applies the new permission model, which it isn't yet prepared to handle (asking for permissions).

**Comment by poisdeux** [comment]
Ah ok, do you have any plans to add support for the new permission model anytime soon?

**Comment by SyncedSynapse** [comment]
Yes, soon (it's not hard, but i haven't had much time lately).

**Comment by poisdeux** [comment]
Don't be fooled by the travis check. This does not work at the moment. Still working on it.

**Comment by SyncedSynapse** [comment]
@poisdeux Can you please confirm if this can be merged? Not sure if there were any changes lately that might conflict with this.

And by the way, creating the directory `tools/jenkins` and moving the jenkins scripts there won't affect the build?

**Comment by poisdeux** [comment]
Rebased on master. Should merge fine now.

I do not have any experience in setting up a jenkins environment. The move might require a configuration change at the server.

**Comment by MartijnKaijser** [comment]
likely only two line changes in jenkins. ping @Memphiz to be sure

**Comment by Memphiz** [comment]
Yes in the Jenkins Job 2 lines in the "execute Shell" steps have to be altered for this. (i guess @MartijnKaijser spotted those already :) ).

**Comment by SyncedSynapse** [comment]
@Memphiz Can you please comment here when the Jenkins Job is changed, so i can merge this. Thanks.

**Comment by MartijnKaijser** [comment]
go ahead and merge

**Comment by MartijnKaijser** [comment]
@Memphiz seems there must be another change as well

**Comment by Memphiz** [comment]
no idea and no time atm

**Comment by Memphiz** [comment]
There doesn't seem to be an apk file built anymore since this pr got merged - at least it is nowhere to be found in the workspace anymore

**Comment by SyncedSynapse** [comment]
@poisdeux Seems like the changes at `build.gradle` are conflicting with generating the release build. Any ideas?

**Comment by SyncedSynapse** [comment]
@Memphiz looking at the output, it seems that `/Users/Shared/jenkins/workspace/Kore/../../android-dev/signing/doreleasesign.sh` might need to be changed (not sure, as i can't see it).

I'm guessing that it pulls the apk from `/Users/Shared/jenkins/workspace/Kore/app/build/outputs/apk/`, signs it and drop it on `/Users/Shared/jenkins/workspace/Kore/kore-release.apk`. With this PR, we need to make sure that it is getting the right apk - it should be signing `app-full-release.apk` (ignore `app-instrumentationTest-release.apk`).

**Comment by Memphiz** [comment]
Will check tomorrow

**Comment by poisdeux** [comment]
Hmm, assumptions are the ........ 
It appears that adding the instrumentationTest flavor resulted in generating ONLY app-instrumentationTest-release.apk. We need to add an extra flavor to generate an APK that does not include the permission needed for testing Kore. I'm still testing this, as it appears the task grantAnimationPermissionDev is executed for each flavor.

**Comment by SyncedSynapse** [comment]
@poisdeux Be advised that i've added a commit on master that adds a new product flavor.

**Comment by Memphiz** [comment]
i think i fixed the signing ... the doreleasesign.sh script checked if the apksign in tools/android/packaging is there before calling it - i have removed that check ... also see my PR - there was a wrong apk name in the tools/jenkins/android/packaging/apksign script.

**Pull request merged**
