### PR TITLE
Implemented restoring list position for AbstractListFragment

### PR DESCRIPTION
**Pull request by poisdeux**

### CODE REVIEW

**Comment by poisdeux** [comment]
Note, this does not include the refactoring of #228 yet. Depending on which gets merged first I will either update this PR or #228.

**Comment by SyncedSynapse** [comment]
What's easier for you? Which one you want me to merge first?

**Comment by poisdeux** [comment]
I think it would be easiest if you merged #228 first.

**Comment by SyncedSynapse** [comment]
#228 merged.

**Comment by poisdeux** [comment]
Updated

**Pull request merged**
