### PR TITLE
Update fr translations

### PR DESCRIPTION
**Pull request by sohelzerdoumi**
I just forgot one key **vibrate_on_remote** because i don't know how to translate it neatly.

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
This breaks the build because some apostrophes aren't preceded by a \ (for instance: `Jouer à partir d'ici` should be `Jouer à partir d\'ici`.

Regarding vibrate_on_remote, wouldn't something like `Vibrer à appuyer sur les boutons` work?

**Comment by sohelzerdoumi** [comment]
I fix apostrophes but no this translation don't work. I don't understand the feature behind the sentence.

**Comment by SyncedSynapse** [comment]
When it is enabled, the buttons on the remote screen (left/right/up/down, etc) vibrate to give a tactical feedback. If you switch it on doesn't it work (assuming your device can vibrate)?

**Comment by sohelzerdoumi** [comment]
I just tried and now i understand the feature. The english sentence is ambiguous, i thought the remote screen was my computer or my raspberry.  But, it seems to be a "vibrate on screen touched".
I will translate the last key now.

**Comment by sohelzerdoumi** [comment]
Translation done.

**Pull request merged**
