### PR TITLE
Translations update from Kodi Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Kodi Weblate](https://kodi.weblate.cloud) for [Kodi remotes/Kore](https://kodi.weblate.cloud/projects/kodi-remotes/kore/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by gade01** [comment]
@SyncedSynapse 
That should be all new languages.
I used Weblate translation memory to do some translations for each language.

Do the folder names work?
They use Android style, but lower case.

**Comment by SyncedSynapse** [comment]
I'll take a detailed look later, but at first sight, this seems ok.

I have one doubt though:
The way Android works is that it gets the translation corresponding to the language that the user's device is set, and developers just need to drop the translation files to the correct folder.
On Kore, besides that, we've added a setting that allows the user to change the language to something else. To make this work, we need to add the language to the set of supported languages on that setting.
Now, the thing is, i believe that most of these new languages are still placeholders, with few strings translated, so it doesn't make much sense to include them in that setting (which will grow by a lot, and be less than user-friendly). What i propose is to add only the languages that are more than, say 50%, translated to that setting.
They would still be available through the system default setting. (Actually i just noticed that there might be a bug, where after changing the language, you can't set it back to "System default", but i'll look into that).

**Comment by gade01** [comment]
@SyncedSynapse 
Ah, I see.
For https://github.com/xbmc/Official-Kodi-Remote-iOS we talked about the exact same thing.
There's no need to add support for a language which isn't translated much.

I fully agree that it makes sense to only add languages that are more than 50% translated to the Kore setting.
In general, some languages are translated very fast, while other languages will never get close to 50% translated.

**Comment by SyncedSynapse** [comment]
Haven't merged this, because i first need to drag Kore's codebase into 2022 to be able to compile it... and time hasn't permitted. Will try to do it this week.

**Comment by gade01** [comment]
@SyncedSynapse No rush on this ;)

**Comment by olavinto** [comment]
I just cleaned and finalized the Finnish translation, so it would be nice if you could update it as well. :-)

**Comment by gade01** [comment]
@olavinto 
Really nice work, thanks so much!
I pushed the changes to this PR.

**Pull request merged**
