### PR TITLE
Fix for long press Info button to display codec info in v17

### PR DESCRIPTION
**Pull request by BSunk**
Fix for issue #285.

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
Thanks. I'm not going to merge this right now because i'm thinking that this sort of issues will happen in the future, so Kodi's version should be present in the local database, to avoid always calling `GetProperties` (and it should be kept up to date seamlessly). Then this PR should just check the `host` version, not needing to call `GetProperties`.

**Comment by MartijnKaijser** [comment]
It should be a one time check imo on initial connection and then it should save it until next connection.

**Comment by SyncedSynapse** [comment]
Ideally yes, but on Kore you don't keep an active connection. Whenever you switch screens (from the remote to any other screen for instance), exit Kore, etc, it closes the connection, and we shouldn't update that info on every connection start.
Maybe keep a date reflecting when the info was last updated and update it on a daily basis.

**Comment by poisdeux** [comment]
We might also naively use the old method and depend on receiving an error response whenever the method isn't implemented. Then update the version and try again. If it still fails we should notify the user.

**Comment by DaveTBlake** [comment]
Why check Kodi version? Why not use the JSON API version instead? Isn't that part of why such version control exists?

**Pull request merged**
