### PR TITLE
Added running lint on travis-ci

### PR DESCRIPTION
**Pull request by poisdeux**
Fixed lint errors regarding calling new methods on older versions

### CODE REVIEW

**Comment by poisdeux** [comment]
Oh thy travis...

Travis seems to have a little trouble running `lintFullRelease`. Debugging now...

**Comment by poisdeux** [comment]
Hmm, can't seem to find what's causing travis to fail. I removed the lint check so this PR now only fixes the lint errors.

For reference see https://travis-ci.org/xbmc/Kore/builds/188278237#L1686

I am unable to reproduce on my machine...

**Comment by SyncedSynapse** [comment]
Do you want to keep this open or can i merge it?

**Comment by poisdeux** [comment]
This can be merged. Was hoping someone would have a clue on what's wrong...

**Pull request merged**
