### PR TITLE
Implemented simple Kodi markup code applier for the Now Playing fragment

### PR DESCRIPTION
**Pull request by monzee**

### CODE REVIEW

**Comment by SyncedSynapse** [comment]
I can merge this as-is, but would you consider making the `format` function a `static` function in `UIUtils`? 

We would avoid creating an object. Not that it makes any difference in here, but this can/should be used in lists (particularly in the PVR channels list), and there it can save something (not much, i agree, but something nevertheless).

PS. If instead of starting at the beginning of the string it started at the first [ (basically what is done in the `else` clause) it would save some cycles on the most common case (not having any markup code).

**Comment by monzee** [comment]
I implemented the suggested changes. Should I add other tags? I don't really know which ones are often seen by the client. These ones are sent by the YouTube plugin (except for `[I]`). From http://kodi.wiki/view/Label_Formatting:
- `[LOWERCASE]` and `[CAPITALIZE]` are trivial to add
- As for `[LIGHT]` I guess this means thinner font? I'm not sure what it means.
- `[COLOR ...]` would be tricky, I don't know what colors could appear there.
- the others I'm not sure if those would even be sent to the client in that form.

**Comment by SyncedSynapse** [comment]
Your call. I can merge this as-is. Other tags can be implemented later.

Though, if you wanted to close #191 you could add the COLOR tag :) My suggestion is to ignore it, just remove it from the string.

**Comment by monzee** [comment]
I think it's ready. I'm going to post a fix for #191 when this is merged.

**Pull request merged**
