### PR TITLE
Use GitHub Actions

### PR DESCRIPTION
**Pull request by mueller-ma**
* Better integration in GitHub
* Travis.org is shutting down: https://blog.travis-ci.com/2021-05-07-orgshutdown (It has to be migrated to travis.com)
* Validate Gradle Wrapper before using it

### CODE REVIEW

**Comment by mueller-ma** [comment]
I had to update Gradle Wrapper, because the previous one has an invalid hashsum.

> If this GitHub action fails because a gradle-wrapper.jar doesn't match one of our published SHA-256 checksums, we highly recommend that you reach out to us at security@gradle.com.

https://github.com/gradle/wrapper-validation-action#reporting-failures

**Comment by mueller-ma** [comment]
Example run: https://github.com/mueller-ma/Kore/runs/2787709554

**Comment by mueller-ma** [comment]
@SyncedSynapse May I ask for a review here?

**Comment by SyncedSynapse** [comment]
I'm sorry, somehow i didn't notice this.

I'll ask someone on the team to help me out with reviewing this, and get back to you soon.

Once again, sorry for leaving this hanging.

**Comment by SyncedSynapse** [comment]
With my limited expertise in this matter, this seems ok.

The only thing i'd like to solve is the Travis issue, and probably the right thing to do is to disable it completely. @MartijnKaijser i believe you initially set up Travis, can you help here?

**Comment by mueller-ma** [comment]
I don't think Travis is connected to this repo anymore. Looking at https://github.com/xbmc/Kore/commits/master I don't see any Travis checks since May 2021.

**Comment by SyncedSynapse** [comment]
You're right, my bad. Will merge this.

**Pull request merged**
